//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedExtension.FeedServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FeedServiceReference.IFeedService")]
    public interface IFeedService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedService/GetFeed", ReplyAction="http://tempuri.org/IFeedService/GetFeedResponse")]
        CommonTypes.FeedItem[] GetFeed();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedService/GetFeed", ReplyAction="http://tempuri.org/IFeedService/GetFeedResponse")]
        System.Threading.Tasks.Task<CommonTypes.FeedItem[]> GetFeedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedService/GetSources", ReplyAction="http://tempuri.org/IFeedService/GetSourcesResponse")]
        string[] GetSources();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedService/GetSources", ReplyAction="http://tempuri.org/IFeedService/GetSourcesResponse")]
        System.Threading.Tasks.Task<string[]> GetSourcesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedService/RemoveSource", ReplyAction="http://tempuri.org/IFeedService/RemoveSourceResponse")]
        void RemoveSource(string source);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedService/RemoveSource", ReplyAction="http://tempuri.org/IFeedService/RemoveSourceResponse")]
        System.Threading.Tasks.Task RemoveSourceAsync(string source);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedService/AddSource", ReplyAction="http://tempuri.org/IFeedService/AddSourceResponse")]
        void AddSource(string source);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedService/AddSource", ReplyAction="http://tempuri.org/IFeedService/AddSourceResponse")]
        System.Threading.Tasks.Task AddSourceAsync(string source);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFeedServiceChannel : FeedExtension.FeedServiceReference.IFeedService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeedServiceClient : System.ServiceModel.ClientBase<FeedExtension.FeedServiceReference.IFeedService>, FeedExtension.FeedServiceReference.IFeedService {
        
        public FeedServiceClient() {
        }
        
        public FeedServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeedServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CommonTypes.FeedItem[] GetFeed() {
            return base.Channel.GetFeed();
        }
        
        public System.Threading.Tasks.Task<CommonTypes.FeedItem[]> GetFeedAsync() {
            return base.Channel.GetFeedAsync();
        }
        
        public string[] GetSources() {
            return base.Channel.GetSources();
        }
        
        public System.Threading.Tasks.Task<string[]> GetSourcesAsync() {
            return base.Channel.GetSourcesAsync();
        }
        
        public void RemoveSource(string source) {
            base.Channel.RemoveSource(source);
        }
        
        public System.Threading.Tasks.Task RemoveSourceAsync(string source) {
            return base.Channel.RemoveSourceAsync(source);
        }
        
        public void AddSource(string source) {
            base.Channel.AddSource(source);
        }
        
        public System.Threading.Tasks.Task AddSourceAsync(string source) {
            return base.Channel.AddSourceAsync(source);
        }
    }
}
